In [6]:
import pandas as pd

# from pandas import Series, DataFrame

row_of_data = [10,20,30,40]
cols=["Nate", "Rebecca", "Edwin", "Preston"]
series_of_data = pd.Series(row_of_data, index=cols)
print(f"list: {row_of_data}")
print(f"series: {series_of_data}")

list: [10, 20, 30, 40]
series: Nate       10
Rebecca    20
Edwin      30
Preston    40
dtype: int64

In [10]:
# dataframm By column

family = {
    "name": ["Nate", "Rebecca", "Edwin", "Preston"],
    "age": [40, 41,12, 8]
}
df1 = pd.DataFrame(data=family)
df1

      name  age
0     Nate   40
1  Rebecca   41
2    Edwin   12
3  Preston    8

In [12]:
#DataFrame by Rows

cols = ["name", "age"] 
row = [
    {"name": "nate", "age": 40},
    {"name": "rebecca", "age": 41},
    {"name": "edwin", "age": 12},
    {"name": "preston", "age": 8}
]
df2 =pd.DataFrame (data=row, columns=cols)
df2

      name  age
0     nate   40
1  rebecca   41
2    edwin   12
3  preston    8

In [14]:
df1["age"]

0    40
1    41
2    12
3     8
Name: age, dtype: int64

In [16]:
df1.mean(numeric_only=True)

age    25.25
dtype: float64

In [17]:
df1["age"]

0    40
1    41
2    12
3     8
Name: age, dtype: int64

In [20]:
df2["name"][2]

'edwin'

In [22]:
df2["gender"] = ["W", "F", "M", "M"]
df2

      name  age gender
0     nate   40      W
1  rebecca   41      F
2    edwin   12      M
3  preston    8      M

In [24]:
df2[["name", "gender"]]

      name gender
0     nate      W
1  rebecca      F
2    edwin      M
3  preston      M

In [25]:
df2.head(2)

      name  age gender
0     nate   40      W
1  rebecca   41      F

In [27]:
df2.isnull().sum()

name      0
age       0
gender    0
dtype: int64

In [28]:
df2.describe()

             age
count   4.000000
mean   25.250000
std    17.689451
min     8.000000
25%    11.000000
50%    26.000000
75%    40.250000
max    41.000000

In [29]:
df2.sort_index()

      name  age gender
0     nate   40      W
1  rebecca   41      F
2    edwin   12      M
3  preston    8      M