In [ ]:
# loops
# rename
# apply
# aggregated

In [ ]:
import pandas as pd

# data = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/french-ambs.csv"
#df = pd.read_csv("data")
#df.head()

   id                name    place  year    lat   long      lat_long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57  55.68, 12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57  55.68, 12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57  55.68, 12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57  55.68, 12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57  55.68, 12.57

In [8]:
!pwd

/Users/brezzy/Documents/python-class/classwork/notebooks

In [ ]:
# ./filename.csv celel path of current folder.filename.csv
# ../ => goes back one folder
#df.to_csv("../data/french-ambs.csv", index=False)

In [10]:
df = pd.read_csv('../data/french-ambs.csv')
df.head

<bound method NDFrame.head of       id                                  name              place  year  \
0      0                    Richer, Christophe            Denmark  1543
1      1                    Richer, Christophe            Denmark  1541
2      2                    Danzay, Charles de            Denmark  1561
3      3                    Danzay, Charles de            Denmark  1563
4      4                    Danzay, Charles de            Denmark  1582
..   ...                                   ...                ...   ...
864  864                     Canossa, Louis de             Venice  1526
865  865                       Vigier, Jacques      Swiss Cantons  1597
866  866                     De Selve, Georges             Venice  1537
867  867  Noailles, François de, Bishop of Dax             Venice  1559
868  868                    Calvimont, Jean de  Holy Roman Empire  1525

       lat   long      lat_long
0    55.68  12.57  55.68, 12.57
1    55.68  12.57  55.68, 12.57
2    55.68  12.57  55.68, 12.57
3    55.68  12.57  55.68, 12.57
4    55.68  12.57  55.68, 12.57
..     ...    ...           ...
864  45.44  12.33  45.44, 12.33
865  46.94   7.45   46.94, 7.45
866  45.44  12.33  45.44, 12.33
867  45.44  12.33  45.44, 12.33
868  48.21  16.36  48.21, 16.36

[869 rows x 7 columns]>

In [11]:
df = df.drop(columns=["lat_long"])
df.head()

   id                name    place  year    lat   long
0   0  Richer, Christophe  Denmark  1543  55.68  12.57
1   1  Richer, Christophe  Denmark  1541  55.68  12.57
2   2  Danzay, Charles de  Denmark  1561  55.68  12.57
3   3  Danzay, Charles de  Denmark  1563  55.68  12.57
4   4  Danzay, Charles de  Denmark  1582  55.68  12.57

In [12]:
df[["name", "place"]]
#df = df[[]]

                                     name              place
0                      Richer, Christophe            Denmark
1                      Richer, Christophe            Denmark
2                      Danzay, Charles de            Denmark
3                      Danzay, Charles de            Denmark
4                      Danzay, Charles de            Denmark
..                                    ...                ...
864                     Canossa, Louis de             Venice
865                       Vigier, Jacques      Swiss Cantons
866                     De Selve, Georges             Venice
867  Noailles, François de, Bishop of Dax             Venice
868                    Calvimont, Jean de  Holy Roman Empire

[869 rows x 2 columns]

In [13]:
df = df[["name", "place", "year"]]
df.head()

                 name    place  year
0  Richer, Christophe  Denmark  1543
1  Richer, Christophe  Denmark  1541
2  Danzay, Charles de  Denmark  1561
3  Danzay, Charles de  Denmark  1563
4  Danzay, Charles de  Denmark  1582

In [16]:
df["place"].unique()

<StringArray>
[          'Denmark',           'England',            'Geneva',
           'Grisons', 'Holy Roman Empire',       'Netherlands',
    'Ottoman Empire',          'Portugal',              'Rome',
          'Scotland',             'Spain',     'Swiss Cantons',
            'Venice',            'Poland',             'Savoy',
           'Ferrara',            'Saxony',           'Tuscany']
Length: 18, dtype: str

In [15]:
df["place"].count()

np.int64(869)

In [22]:
#Loops
#iterrows/ ilertuples
#iterrows
for idx, row in df.iterrows():
    if row["place"] == "Holy Roman Empire":
        df.at[idx, "place"] = "HRE"
        
df["place"].unique()

<StringArray>
[       'Denmark',        'England',         'Geneva',        'Grisons',
            'HRE',    'Netherlands', 'Ottoman Empire',       'Portugal',
           'Rome',       'Scotland',          'Spain',  'Swiss Cantons',
         'Venice',         'Poland',          'Savoy',        'Ferrara',
         'Saxony',        'Tuscany']
Length: 18, dtype: str

In [31]:
for row in df.itertuples():
    idx = row.Index
    if row.place == "Ottoman Empire":
        df.at[idx,"place"] = "Ott"
        
df["place"].unique()

<StringArray>
[      'Denmark',       'England',        'Geneva',       'Grisons',
           'HRE',   'Netherlands',           'Ott',      'Portugal',
          'Rome',      'Scotland',         'Spain', 'Swiss Cantons',
        'Venice',        'Poland',         'Savoy',       'Ferrara',
        'Saxony',       'Tuscany']
Length: 18, dtype: str

In [33]:
# complicated boolean logic with l (or), & (and), ~ (Not)
df.loc[~((df["place"] == "netherlands") | (df["place"] == "England")) & (df["year"] < 1550)]

                         name          place  year
0          Richer, Christophe        Denmark  1543
1          Richer, Christophe        Denmark  1541
16   Castion, Jean-Jacques de        Grisons  1543
27    d'Aramon, Gabriel Leutz            Ott  1548
32            De Caix, Honoré       Portugal  1534
..                        ...            ...   ...
854          Daugerant, Louis  Swiss Cantons  1537
861          Montluc, Jean de         Venice  1542
864         Canossa, Louis de         Venice  1526
866         De Selve, Georges         Venice  1537
868        Calvimont, Jean de            HRE  1525

[238 rows x 3 columns]

In [34]:
# using .loc to replace

df.loc[df["place"] == "Netherlands", "place"] = "Neth"
df["place"].unique()

<StringArray>
[      'Denmark',       'England',        'Geneva',       'Grisons',
           'HRE',          'Neth',           'Ott',      'Portugal',
          'Rome',      'Scotland',         'Spain', 'Swiss Cantons',
        'Venice',        'Poland',         'Savoy',       'Ferrara',
        'Saxony',       'Tuscany']
Length: 18, dtype: str

In [35]:
#replace many with a hash using .replace()
hash = {place: f"{place[:3] + '.' if len(place) > 4 else place}" for place in df["place"].unique()}
df["place"] = df["place"].replace(hash)

In [36]:
df["place"].unique()

<StringArray>
['Den.', 'Eng.', 'Gen.', 'Gri.',  'HRE', 'Neth',  'Ott', 'Por.', 'Rome',
 'Sco.', 'Spa.', 'Swi.', 'Ven.', 'Pol.', 'Sav.', 'Fer.', 'Sax.', 'Tus.']
Length: 18, dtype: str

In [ ]:
#.apply() takes a function